name: ulak_updater
description: Self-hosted in-app updater for Android Flutter apps. Version check, download, sha256 verify, REQUEST_INSTALL_PACKAGES one-tap install.
version: 0.1.1
repository: https://github.com/yunusemrealpak/ulak_updater
issue_tracker: https://github.com/yunusemrealpak/ulak_updater/issues

topics:
  - updater
  - apk
  - android
  - self-hosted

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dio: ^5.5.0
  fpdart: ^1.1.0
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  package_info_plus: ^8.0.0
  crypto: ^3.0.5
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.tepvox.ulak_updater
        pluginClass: UlakUpdaterPlugin
